### ISSUE TITLE
TypeError in the DriverFactory when use AttributeDriver

### ISSUE THREAD

**Issue by defaultpage** [skar/laminas-doctrine-orm#2]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  |  v0.1

#### Summary
When I use `\Doctrine\ORM\Mapping\Driver\AttributeDriver`, I get an error:

> Uncaught TypeError: Doctrine\ORM\Mapping\Driver\AttributeDriver::__construct(): Argument # 1 ($paths) must be of type array, Doctrine\Common\Annotations\CachedReader given, called in ... vendor\skar\laminas-doctrine-orm\src\Service\DriverFactory.php on line 49...

#### How to reproduce

1. 
```php
// config/autoload/orm.global.php

<?php

declare(strict_types=1);

return [
    'doctrine' => [
        'connection' => [
            'orm_default' => [
                'driver_class' => \Doctrine\DBAL\Driver\PDO\MySQL\Driver::class,
            ],
        ],
    ],
];
```
2. 
```php
// local.php

<?php

/**
 * Local configuration.
 *
 * Copy this file to `local.php` and change its settings as required.
 * `local.php` is ignored by git and safe to use for local and sensitive data like usernames and passwords.
 */

declare(strict_types=1);

return [
    'doctrine' => [
        'connection' => [
            'orm_default' => [
                'params' => [
                    'host'     => '<host>',
                    'port'     => '<port>',
                    'user'     => '<user>',
                    'password' => '<pass>',
                    'dbname'   => '<dbname>',
                ],
            ],
        ],
    ],
];

```
3. Run `vendor/bin/laminas doctrine:migrations:diff`

**Comment by skar** [comment]
Thanks! Maybe this part should be rewritten in the future, but for now this should work.
