### ISSUE TITLE
Uncaught Error: Class "Doctrine\Common\Cache\ArrayCache" not found

### ISSUE THREAD

**Issue by editorfatih** [skar/laminas-doctrine-orm#5]
Hi, i'm using mezzio 3.9.0.

I prepared the configuration as in README (not different) but it throws error.

`> laminas --ansi 'doctrine:migrations:diff'
PHP Fatal error:  Uncaught Error: Class "Doctrine\Common\Cache\ArrayCache" not found in [base_dir]/vendor/skar/laminas-doctrine-orm/src/Service/CacheFactory.php:38
Stack trace:
#0 [base_dir]/vendor/skar/laminas-doctrine-orm/src/Service/ServiceAbstractFactory.php(59): Skar\LaminasDoctrineORM\Service\CacheFactory->__invoke()
#1 [base_dir]/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(613): Skar\LaminasDoctrineORM\Service\ServiceAbstractFactory->__invoke()
#2 [base_dir]/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(234): Laminas\ServiceManager\ServiceManager->doCreate()
#3 [base_dir]/vendor/skar/laminas-doctrine-orm/src/Service/ConfigurationFactory.php(57): Laminas\ServiceManager\ServiceManager->get()
#4 [base_dir]/vendor/skar/laminas-doctrine-orm/src/Service/ServiceAbstractFactory.php(59): Skar\LaminasDoctrineORM\Service\ConfigurationFactory->__invoke()
#5 [base_dir]/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(613): Skar\LaminasDoctrineORM\Service\ServiceAbstractFactory->__invoke()
#6 [base_dir]/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(234): Laminas\ServiceManager\ServiceManager->doCreate()
#7 [base_dir]/vendor/skar/laminas-doctrine-orm/src/Service/ConnectionFactory.php(28): Laminas\ServiceManager\ServiceManager->get()
#8 [base_dir]/vendor/skar/laminas-doctrine-orm/src/Service/ServiceAbstractFactory.php(59): Skar\LaminasDoctrineORM\Service\ConnectionFactory->__invoke()
#9 [base_dir]/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(613): Skar\LaminasDoctrineORM\Service\ServiceAbstractFactory->__invoke()
#10 [base_dir]/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(234): Laminas\ServiceManager\ServiceManager->doCreate()
#11 [base_dir]/vendor/skar/laminas-doctrine-orm/src/Service/EntityManagerFactory.php(20): Laminas\ServiceManager\ServiceManager->get()
#12 [base_dir]/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(613): Skar\LaminasDoctrineORM\Service\EntityManagerFactory->__invoke()
#13 [base_dir]/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(234): Laminas\ServiceManager\ServiceManager->doCreate()
#14 [base_dir]/vendor/skar/laminas-doctrine-orm/src/Command/MigrationsCommandTrait.php(37): Laminas\ServiceManager\ServiceManager->get()
#15 [base_dir]/vendor/symfony/console/Command/Command.php(264): Skar\LaminasDoctrineORM\Command\MigrationsDiff->initialize()
#16 [base_dir]/vendor/symfony/console/Application.php(1033): Symfony\Component\Console\Command\Command->run()
#17 [base_dir]/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#18 [base_dir]/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#19 [base_dir]/vendor/laminas/laminas-cli/bin/laminas(53): Symfony\Component\Console\Application->run()
#20 [base_dir]/vendor/bin/laminas(107): include('...')
#21 {main}
  thrown in [base_dir]/vendor/skar/laminas-doctrine-orm/src/Service/CacheFactory.php on line 38
Script laminas --ansi handling the mezzio event returned with error code 255`

i think it related to doctrine-cache module, maybe requires psr-6 compatible cache container, doesn't it work without cache container ?

**Comment by skar** [comment]
Hi,

What version are you use? `0.1` or `dev-master`?
In Doctrine was removed Cache implementations.
Try `0.1` and older version of Doctrine.
I will prepare an update this week for new version of Doctrine.

**Comment by editorfatih** [comment]
> Hi,
> 
> What version are you use? `0.1` or `dev-master`? In Doctrine was removed Cache implementations. Try `0.1` and older version of Doctrine. I will prepare an update this week for new version of Doctrine.

Hi, 
it doesn't matter, i did try `dev-master` and `0.1` , results are same...
it may be related to removed implementation

**Comment by skar** [comment]
Try to fix the Doctrine Cache to version 1.x.x in the your composer.json file, something like that: `"doctrine/cache": "^1.12.1"`

**Comment by editorfatih** [comment]
Thank you for your reply. Issue resolved when adding these packages to our requirements

`"doctrine/annotations": "1.13.2"`
`"doctrine/cache": "1.12.1",`
